### ISSUE TITLE
Accessing KeyValueDataType

### ISSUE THREAD

**Issue by muteb** [janstarke/nt-hive2#4]
Hi Jan,
I'm playing around with the  lib and I was trying to get the data type of a value such as "REG_SZ". I tried to modify the code and the field marked as private field and I really don't want to miss up with the code :). 
```

for sk in root_key.subkeys(&mut hive)?.iter() {
    println!("\n[{}]; last written: {}", sk.borrow().name(), sk.borrow().timestamp());
    for value in sk.borrow().values() {
        println!("\"{}\" = {} ={}", value.name(), value.value() ,**value.data_type()**);
    }
}
```
Thanks,

**Comment by muteb** [comment]
for my use case, the generic way such as "REG_SZ" or "REG_expand_SZ" would serve me well, however, what you have proposed is also nice to have. either one should be helpful. 
thanks Jan,

**Comment by janstarke** [comment]
the REG format only knows plain Strings, `dword` and `hex`, which is insufficient in my eyes. So, with exposing the real datatypes, we violate the original format. Because we know we are not fully compatible to the original format, we can choose a format which matches our needs best. So please feel free to propose your preferred solution

**Comment by muteb** [comment]
I really liked the one you pushed into the repo and it servers me well. thanks Jan
